"""Small instances built by hand to pin one behaviour each.

Every expected answer here is worked out on paper — the day-by-day balances are
in the comments — rather than read off the engine under test. An expectation
generated by the code it checks proves only that the code is consistent with
itself, which is how a wrong rule survives its own test suite.

They are kept tiny (a handful of days, at most six candidates) precisely so the
arithmetic can be checked by eye.
"""

from __future__ import annotations

from typing import Any


def txn(tid: str, day: str, cents: int, kind: str = "discretionary") -> dict[str, Any]:
    return {
        "id": tid,
        "date": f"2026-03-{day}",
        "description": tid.upper(),
        "amount_cents": cents,
        "kind": kind,
        "recurring": False,
    }


def cand(
    cid: str,
    target: str,
    freed: int,
    day: str,
    *,
    pain: int = 2,
    lead: int = 0,
    recharge: str | None = None,
) -> dict[str, Any]:
    return {
        "id": cid,
        "label": f"Change {cid}",
        "detail": target.upper(),
        "action": "defer" if recharge else "skip",
        "target_txn_id": target,
        "freed_cents": freed,
        "effective_date": f"2026-03-{day}",
        "recharge_date": f"2026-03-{recharge}" if recharge else None,
        "lead_time_days": lead,
        "pain": pain,
    }


def req(
    *,
    days_end: str,
    opening: int,
    buffer: int,
    scheduled: list[dict[str, Any]],
    candidates: list[dict[str, Any]],
    locks: dict[str, list[str]] | None = None,
    previous: list[str] | None = None,
    as_of: str = "01",
) -> dict[str, Any]:
    return {
        "as_of": f"2026-03-{as_of}",
        "horizon_end": f"2026-03-{days_end}",
        "opening_balance_cents": opening,
        "buffer_cents": buffer,
        "scheduled": scheduled,
        "candidates": candidates,
        "locks": locks or {"in": [], "out": []},
        "previous_plan": previous or [],
    }


# Do nothing:  100.00 | -50.00 | -50.00 |  150.00 | 150.00
# The dip is on the 2nd, so only a change that lands BEFORE it can help.
# c_big frees four times as much but arrives on the 4th, after the damage.
# A "cancel the biggest thing first" heuristic takes c_big and then still needs
# c_small: two changes where one does.
GREEDY_FAILS = req(
    days_end="05",
    opening=10_000,
    buffer=0,
    scheduled=[txn("t_1", "02", -15_000), txn("t_2", "04", -20_000), txn("t_pay", "04", 40_000, "income")],
    candidates=[cand("c_small", "t_1", 5_000, "01"), cand("c_big", "t_2", 20_000, "04")],
)
GREEDY_FAILS_PLAN = ["c_small"]  # 150.00 | 0.00 | 0.00 | 200.00 | 200.00


# Do nothing: 100.00 | 10.00 | 0.00   — clears zero, but the 50.00 cushion is gone.
# Neither change alone reaches the cushion; together they do. So the plan is two
# changes, and NEITHER is load-bearing: drop either one and the balance is still
# at or above zero. The certificate must say so rather than claim a proof.
CUSHION_ONLY = req(
    days_end="03",
    opening=10_000,
    buffer=5_000,
    scheduled=[txn("t_1", "02", -9_000), txn("t_2", "03", -1_000)],
    candidates=[cand("c_a", "t_1", 4_000, "01"), cand("c_b", "t_2", 1_000, "01")],
)
CUSHION_ONLY_PLAN = ["c_a", "c_b"]  # 150.00 | 60.00 | 50.00


# Do nothing: 0.00 | -100.00 | -100.00. The only change frees 40.00, so even
# taking everything on offer leaves a 60.00 hole on the 2nd.
TIER3_EVERYTHING = req(
    days_end="03",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "02", -10_000)],
    candidates=[cand("c_a", "t_1", 4_000, "01")],
)
TIER3_EVERYTHING_PLAN = ["c_a"]  # 40.00 | -60.00 | -60.00, needs 60.00 by the 2nd


# The same account with its one change ruled out: the plan is empty and the gap
# is 100.00. The certificate must not say "the schedule already clears".
TIER3_NOTHING_AVAILABLE = req(
    days_end="03",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "02", -10_000)],
    candidates=[cand("c_a", "t_1", 4_000, "01")],
    locks={"in": [], "out": ["c_a"]},
)


# Two ways to change one charge. Taking both would free 120.00 from a 100.00
# charge and report the account clear; only one may be chosen, so the honest
# answer is tier 3 with 40.00 still missing.
SAME_TXN_TWICE = req(
    days_end="03",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "02", -10_000)],
    candidates=[cand("c_a", "t_1", 6_000, "01"), cand("c_b", "t_1", 6_000, "01")],
)


# Both changes pinned, both on the same charge. Honour the lower id and report
# the other as excluded rather than refusing the request.
BOTH_PINNED_SAME_TXN = req(
    days_end="03",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "02", -10_000)],
    candidates=[cand("c_a", "t_1", 6_000, "01"), cand("c_b", "t_1", 6_000, "01")],
    locks={"in": ["c_a", "c_b"], "out": []},
)


# Two changes that are identical on every scored term. Nothing but the tiebreak
# separates them, which is exactly when a solver is free to answer differently
# on two runs.
IDENTICAL_PAIR = req(
    days_end="03",
    opening=5_000,
    buffer=0,
    scheduled=[txn("t_1", "02", -5_000), txn("t_2", "02", -5_000)],
    candidates=[cand("c_a", "t_1", 5_000, "01"), cand("c_b", "t_2", 5_000, "01")],
)
IDENTICAL_PAIR_REMEMBERED = req(
    days_end="03",
    opening=5_000,
    buffer=0,
    scheduled=[txn("t_1", "02", -5_000), txn("t_2", "02", -5_000)],
    candidates=[cand("c_a", "t_1", 5_000, "01"), cand("c_b", "t_2", 5_000, "01")],
    previous=["c_b"],
)


# Same cost, different disruption: among equally small plans the gentler one wins.
PAIN_BREAKS_THE_TIE = req(
    days_end="03",
    opening=5_000,
    buffer=0,
    scheduled=[txn("t_1", "02", -5_000), txn("t_2", "02", -5_000)],
    candidates=[
        cand("c_a", "t_1", 5_000, "01", pain=5),
        cand("c_b", "t_2", 5_000, "01", pain=1),
    ],
)


# The horizon ends the day before payday, so the dip on the final day is real
# and must be planned for. An off-by-one here hides an overdraft at the single
# riskiest moment of the month.
PAYDAY_EVE = req(
    days_end="04",
    opening=10_000,
    buffer=0,
    scheduled=[txn("t_1", "04", -12_000)],
    candidates=[cand("c_a", "t_1", 2_000, "01")],
)
# 100.00 | 100.00 | 100.00 | -20.00  ->  with c_a: 120.00 ... 0.00


# A deferral that pays itself back after the horizon ends: inside the window the
# money simply stays. Getting this wrong invents a charge that never lands.
DEFER_PAST_HORIZON = req(
    days_end="03",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "02", -5_000)],
    candidates=[cand("c_a", "t_1", 5_000, "01", recharge="20")],
)


# Two days equally deep. The reported worst day is the FIRST of them, because a
# deadline you have already missed is not a deadline.
TWO_EQUAL_DIPS = req(
    days_end="04",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "02", -5_000), txn("t_2", "03", 5_000, "income"), txn("t_3", "04", -5_000)],
    candidates=[cand("c_a", "t_1", 1_000, "01")],
)


# Cancelling today does not stop tomorrow's charge. c_late needs three days'
# notice and only has two, so it is not on the table however useful it looks.
LEAD_TIME_BOUNDARY = req(
    days_end="05",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "04", -10_000), txn("t_2", "04", -10_000)],
    candidates=[
        cand("c_ok", "t_1", 10_000, "04", lead=3),
        cand("c_late", "t_2", 10_000, "03", lead=3),
    ],
)


# --- pinning the objective order, one adjacent pair at a time ---------------

# Two ways to change one $50 charge, so at most one may be taken.
#   do nothing:  -2.00 | -2.00 | -52.00      three days under, worst 52.00
#   c_early:      2.00 |  2.00 | -48.00      ONE day under,    worst 48.00
#   c_deep:      -2.00 | -2.00 |  -4.00      three days under, worst  4.00
# Fee-triggering days rank above the depth of the dip, so c_early wins: three
# overdraft fees hurt more than one deeper one. Swap those two terms and c_deep
# wins instead, which is how this pins the order.
DAYS_BEAT_DEPTH = req(
    days_end="03",
    opening=200,
    buffer=0,
    scheduled=[txn("t_1", "01", -400), txn("t_2", "03", -5_000)],
    candidates=[
        cand("c_deep", "t_2", 4_800, "03"),
        cand("c_early", "t_2", 400, "01"),
    ],
)
DAYS_BEAT_DEPTH_PLAN = ["c_early"]


# Both changes free the same money on the same day and leave the account in an
# identical state; only disruption and churn separate them. The user was last
# shown c_a, which hurts most. Disruption ranks above churn, so the answer moves
# to c_b — the tool should not keep recommending something painful purely
# because it recommended it last time.
PAIN_BEATS_MEMORY = req(
    days_end="03",
    opening=5_000,
    buffer=0,
    scheduled=[txn("t_1", "02", -5_000), txn("t_2", "02", -5_000)],
    candidates=[
        cand("c_a", "t_1", 5_000, "01", pain=5),
        cand("c_b", "t_2", 5_000, "01", pain=1),
    ],
    previous=["c_a"],
)
PAIN_BEATS_MEMORY_PLAN = ["c_b"]


# A deferral that pays itself back INSIDE the horizon, on a day that matters.
#   with c_a:  50.00 | 0.00 | -50.00 | -50.00
# The money is gone again from the recharge day onward. Crediting that day by
# mistake would report the account clear when it is fifty dollars under.
DEFER_LANDS_IN_HORIZON = req(
    days_end="04",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "02", -5_000)],
    candidates=[cand("c_a", "t_1", 5_000, "01", recharge="03")],
)
DEFER_LANDS_IN_HORIZON_BALANCES = [5_000, 0, -5_000, -5_000]


# A plan row at tier 3 whose removal would cost nothing, so the reason line has
# to be the gap variant rather than "not to clear zero" — nothing clears zero
# here.
#
#   do nothing:  60.00 | 40.00 | -160.00
#   with c_hold: 60.00 | 60.00 | -160.00
#
# c_hold defers the 20.00 charge from the 2nd and hands it back on the 3rd, so
# it lifts the 2nd to the 50.00 cushion and leaves the 3rd exactly where it was.
# Marginals are zero on both terms, and the 200.00 charge on the 3rd is beyond
# anything on offer, so the account is tier 3 whatever is done.
#
# It is PINNED, and it has to be. The objective ranks cardinality above
# below-cushion exposure, and `buffer_missed` is already 1 at tier 3 because the
# balance is under zero, let alone under the cushion. So for any freely chosen
# tier 3 plan, dropping a zero-marginal row ties on days below zero, on the
# worst shortfall and on buffer-missed while strictly lowering the count: the
# smaller plan always wins. A tier 3 row with zero marginals is therefore
# reachable only when the caller pins it in, which `locks.in` is exactly for.
TIER3_CUSHION_ONLY = req(
    days_end="03",
    opening=6_000,
    buffer=5_000,
    scheduled=[txn("t_a", "02", -2_000), txn("t_b", "03", -20_000)],
    candidates=[cand("c_hold", "t_a", 2_000, "01", recharge="03")],
    locks={"in": ["c_hold"], "out": []},
)


# Two changes whose removal costs exactly the same. The sentence names one of
# them, and which one must not depend on solver internals.
EQUAL_MARGINALS = req(
    days_end="03",
    opening=0,
    buffer=0,
    scheduled=[txn("t_1", "02", -4_000), txn("t_2", "02", -4_000)],
    candidates=[cand("c_a", "t_1", 4_000, "01"), cand("c_b", "t_2", 4_000, "01")],
)
